### ISSUE TITLE
Is there a way to suppress creation of logs in .\data\logs ?

### ISSUE THREAD

**Issue by maelcum** [portapps/vscodium-portable#20]
### Behaviour

VSCodium is creating logs although parameter to disable that has been set [to true].

I do not think this is a bug, but the only template available is "Issue: Bug report". Please reclassify if necessary.

#### Steps to reproduce this issue

1. set parameter `disable_log: true` in `vscodium-portable.yml`
2. clear out all logs from .\data\logs
3. start vscodium.cmd or vscodium-portable.exe

#### Expected behaviour

No additional logs in folder `.\data\logs` on the portable media where VSCodium-Portable is located.

#### Actual behaviour

New logs like:
exthost1
output_1_20201007T114140
output_1_20201007T114348
main.log
renderer1.log
sharedprocess.log
telemetry.log
userDataSync.log

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** :

vscodium-portable-win64-1.49.3-48

**Operating system (ex. Windows 10 Pro 64 bits)** :

Windows 10 Enterprise x64 Build 19041.508, Lang EN

**vscodium-portable.yml, derived from vscodium-portable.sample.yml** :
```
common:
  disable_log: true
  args: []
  env: {}
  app_path: ""
app:
  cleanup: false
```

### Logs

Join the log file `log\[appname]-portable.log` to this issue.

There is no such file. Probably the only one not being created by the parameter `disable_log: true`. Is there a way to disable logging alltogether?

**Comment by crazy-max** [comment]
Duplicate #21
