### ISSUE TITLE
Question about running portable VSCodium / VSCode via exe or cmd

### ISSUE THREAD

**Issue by GeniusBroccoli** [portapps/vscodium-portable#29]
Hi. I couldn't find a better place to ask my question, so I'll try to ask it here. In vscodium-portable I see an .exe file and a .cmd file, they both finally run the program. What is the difference between them and which launch method should I use?
And I would also like to point out that after launching in the appdata/roaming folder there is a VSCodium folder with an empty Dictionaries folder in it.
Thank you in advance.

**Comment by crazy-max** [comment]
> In vscodium-portable I see an .exe file and a .cmd file, they both finally run the program. What is the difference between them and which launch method should I use?

`vscodium.cmd` is the [Command Line Interface (CLI)](https://code.visualstudio.com/docs/editor/command-line) like `code.cmd` for Visual Studio Code.

> And I would also like to point out that after launching in the appdata/roaming folder there is a VSCodium folder with an empty Dictionaries folder in it.

See the [Configuration section](https://portapps.io/app/vscodium-portable/#configuration) to cleanup leftovers.
