### ISSUE TITLE
Updating to the latest version ???

### ISSUE THREAD

**Issue by anselal** [portapps/vscodium-portable#33]

**Comment by sergeevabc** [comment]
Dear @crazy-max, what's the proper way to update VSCodium Portable besides using your installer? You see, the current official binary is 1.7.2 from October '22.

**Comment by crazy-max** [comment]
@sergeevabc

* https://portapps.io/doc/contribute/#requirements
* https://portapps.io/doc/contribute/#build

* Put version you want to build like done in `build.properties` https://github.com/portapps/vscodium-portable/commit/a47e86b2b0257017eb0108cda0e9b594afe3a82b
* Run `ant release`

**Comment by sergeevabc** [comment]
It looks more complicated than I originally thought. I'll wait for a fresh installer.
Thank you, @crazy-max.

**Comment by sergeevabc** [comment]
By the way, @crazy-max do you have any schedule on rolling out fresh portables of VSCodium? Specifically, when should we expect the new one?
