### ISSUE TITLE
Should it have `code.cmd` or `codium.cmd`?

### ISSUE THREAD

**Issue by angelog0** [portapps/vscodium-portable#4]
I see that the VSCode package in Portapps has the script `code.cmd`. Should VSCodium have something similar, say `coduim.cmd`? Thanks.

**Comment by crazy-max** [comment]
@angelog0 Yes, it's conceivable.

**Comment by angelog0** [comment]
Thanks, it seems fixed now.

Maybe you can close this.

Thanks.
