### ISSUE TITLE
wrong releases number in release 1.43.0-37

### ISSUE THREAD

**Issue by anselal** [portapps/vscodium-portable#5]
hi there,

I downloaded the latest release (1.43.0-37) and I noticed that in the about window the version appears as 1.44.0 (see attachment below)

![2020-03-13_22h39_35](https://user-images.githubusercontent.com/8732668/76658005-cb097980-657b-11ea-8a02-79c92e09707d.png)

**Comment by crazy-max** [comment]
Hi @anselal, this is an upstream issue. See VSCodium/vscodium#352 and microsoft/vscode#92403

**Comment by anselal** [comment]
Οκ, θενξ.

You can close it I guess
